const seed = [
 {id:1,title:'Помочь пациентам быстрее записываться к врачу',theme:'HealthTech',company:'MedCare',context:'В клинике растёт число звонков и отменённых записей.',need:'Сделать путь пациента к записи понятным и быстрым.',users:'Пациенты клиники и администраторы',data:'Анонимная статистика звонков и записи за 6 месяцев',constraints:'Прототип за 4 недели, без доступа к медицинским картам',result:'Интерактивный прототип сервиса записи',success:'Снизить число звонков на 20% в тестовом сценарии',contact:'Айша, weekly-консультация в Zoom',score:92},
 {id:2,title:'Снизить пищевые отходы в университетских столовых',theme:'EcoTech',company:'Green Campus',context:'Столовые списывают значительное количество готовой еды.',need:'Найти способ прогнозировать спрос и сокращать списания.',users:'Студенты, сотрудники столовых',data:'Продажи блюд по дням, меню и календарь событий',constraints:'6 недель, решение должно быть простым для персонала',result:'Дашборд прогноза и план пилота',success:'Сокращение списаний на 15%',contact:'Данияр, очная встреча раз в неделю',score:78},
 {id:3,title:'Сделать финансовую грамотность ближе студентам',theme:'FinTech',company:'Qadam Bank',context:'Молодые клиенты редко используют полезные финансовые продукты.',need:'Создать вовлекающий формат обучения личным финансам.',users:'Студенты 17–23 лет',data:'Результаты опроса, брендбук и обезличенная аналитика',constraints:'Мобильный web-прототип, 5 недель',result:'Концепт и кликабельный прототип',success:'Не менее 70% пользователей понимают базовые термины',contact:'Мади, чат в Telegram',score:74},
 {id:4,title:'Навигатор по возможностям для первокурсников',theme:'EdTech',company:'UniStart',context:'Первокурсники не знают о клубах, грантах и сервисах вуза.',need:'Собрать информацию в одном дружелюбном продукте.',users:'Первокурсники',data:'Список сервисов и интервью со студентами',constraints:'Нужна интеграция с существующим сайтом',result:'UX-концепция и MVP-каталог',success:'Пройти onboarding меньше чем за 3 минуты',contact:'Салтанат, офлайн демо',score:58},
 {id:5,title:'Удобная обратная связь о городских проблемах',theme:'Smart City',company:'Городская лаборатория',context:'Жители сообщают о проблемах в разных каналах.',need:'Понять, как собрать обращения в одном месте.',users:'Жители города, операторы 109',data:'Пока только примеры обращений',constraints:'Требования к доступности ещё уточняются',result:'Исследование и концепт сервиса',success:'Нужно сформулировать вместе с командой',contact:'Контакт будет назначен после первого созвона',score:35}
];
const weights={context:10,need:10,data:20,result:15,success:15,constraints:10,users:10,contact:10};
let tasks=JSON.parse(localStorage.getItem('impact-tasks')||'null')||seed, current=null, selectedTheme='all';
let offers=JSON.parse(localStorage.getItem('impact-offers')||'null')||[{id:1,taskId:1,team:'Byte Busters',idea:'Сервис записи с понятным выбором врача и времени.',plan:'Исследование → UX → кликабельный MVP',term:'4 недели',link:'https://figma.com/prototype',status:'new'},{id:2,taskId:1,team:'MedMinds',idea:'Чат-помощник для первичной навигации пациента.',plan:'Интервью → сценарии → тестирование',term:'3 недели',link:'https://github.com',status:'new'},{id:3,taskId:2,team:'EcoWaves',idea:'Прогнозирование спроса на блюда по данным продаж.',plan:'Анализ данных → дашборд → пилот',term:'5 недель',link:'https://github.com',status:'new'}];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const save=()=>{localStorage.setItem('impact-tasks',JSON.stringify(tasks));localStorage.setItem('impact-offers',JSON.stringify(offers))};
function level(score){return score>=90?'priority':score>=70?'ready':score>=40?'working':'draft'} function levelName(s){return {priority:'Приоритетная',ready:'Готовая',working:'Рабочая',draft:'Черновик'}[level(s)]}
function calculate(t){return Object.entries(weights).reduce((n,[k,w])=>n+(t[k]&&t[k].trim().length>8?w:0),0)}
function show(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('#view-title').textContent={catalog:'Каталог',create:'Новая задача',offers:'Предложения',questions:'AI-уточнение',card:'Карточка',detail:'Задача'}[id]||'Платформа';window.scrollTo(0,0)}
function renderCatalog(){let list=tasks.filter(t=>(selectedTheme==='all'||t.theme===selectedTheme)&&($('#readiness-filter').value==='all'||level(t.score)===$('#readiness-filter').value)).sort((a,b)=>b.score-a.score);$('#task-count').textContent=`${tasks.length} задач`;$('#task-grid').innerHTML=list.map(t=>`<article class="task"><div class="task-meta"><span class="tag">${t.theme}</span><span class="readiness ${level(t.score)}">${levelName(t.score)}</span></div><h3>${t.title}</h3><p>${t.need||t.context}</p><div class="task-foot"><span class="score-pill"><b>${t.score}</b>/100</span><button class="view-link" data-task="${t.id}">Смотреть →</button></div></article>`).join('')||'<p>По этим фильтрам задач пока нет.</p>'}
function questions(){let q=[['users','Кто будет пользоваться будущим решением?','Например: пациенты 25–50 лет и администраторы клиники'],['data','Какие данные, примеры или материалы вы готовы предоставить команде?','Например: анонимная статистика, интервью, ссылки, брендбук'],['success','По каким измеримым признакам вы поймёте, что решение удалось?','Например: сократить время на запись на 30%'],['constraints','Какие есть ограничения: сроки, технологии, доступы, бюджет?','Например: прототип за 4 недели, без персональных данных']];$('#questions-form').innerHTML=q.map(([id,q,p],i)=>`<div class="question"><b>${i+1}. ${q}</b><textarea data-field="${id}" placeholder="${p}" rows="3"></textarea></div>`).join('')}
function scoreDetails(t){return Object.entries(weights).map(([key,w])=>{let exists=t[key]&&t[key].trim().length>8;let labels={context:'Контекст',need:'Потребность',data:'Данные и материалы',result:'Ожидаемый результат',success:'Критерии успеха',constraints:'Ограничения',users:'Пользователи',contact:'Связь с бизнесом'};return `<div class="score-row"><div><span>${labels[key]}</span><b>${exists?w:0}/${w}</b></div><div class="bar"><i style="width:${exists?100:0}%"></i></div></div>`}).join('')}
function renderCard(){let t=current;t.score=calculate(t);$('#score-panel').innerHTML=`<div class="score">${t.score}<small>/100</small></div><p>${levelName(t.score)} задача</p>`;$('#score-details').innerHTML=scoreDetails(t);let fields=[['title','Название задачи','Например, сервис записи к врачу'],['context','Контекст: что происходит сейчас?','Опишите текущую ситуацию'],['need','Потребность: что нужно изменить?','Какую проблему решаем'],['users','Пользователи','Для кого создаётся решение'],['data','Данные и материалы','Что вы можете предоставить'],['constraints','Ограничения','Сроки, технологии, доступы'],['result','Ожидаемый результат','Что должна создать команда'],['success','Критерии успеха','Как измерите результат'],['contact','Контакт и формат взаимодействия','Имя, канал связи, частота консультаций']];$('#card-form').innerHTML=fields.map(([key,label,ph])=>`<label>${label}<textarea data-card="${key}" placeholder="${ph}" rows="${key==='title'?1:3}">${t[key]||''}</textarea></label>`).join('')}
function detail(id){current=tasks.find(t=>t.id==id);let t=current;$('#detail-content').innerHTML=`<div class="detail-hero"><div class="detail-top"><span class="tag">${t.theme}</span><span class="readiness ${level(t.score)}">${levelName(t.score)} · ${t.score}/100</span></div><h1>${t.title}</h1><p class="intro">${t.need}</p></div><div class="detail-content"><div>${[['Контекст',t.context],['Пользователи',t.users],['Данные и материалы',t.data],['Ожидаемый результат',t.result],['Критерии успеха',t.success],['Ограничения',t.constraints]].map(x=>`<div class="info-block"><h3>${x[0]}</h3><p>${x[1]||'Не указано'}</p></div>`).join('')}</div><aside class="detail-side"><h3>Есть идея решения?</h3><p>Отправьте предложение. Бизнес сам сравнит все отклики и примет решение.</p><button class="primary" id="open-offer">Откликнуться <span>→</span></button><p><b>Контакт:</b><br>${t.contact||'Уточняется'}</p></aside></div>`;show('detail')}
function renderOffers(){let mine=offers;$('#offers-content').innerHTML=mine.length?`<div class="offer-list">${mine.map(o=>{let t=tasks.find(x=>x.id===o.taskId);return `<article class="offer"><div><span class="tag">${t?.title||'Задача'}</span><h3>${o.team}</h3><p><b>Идея:</b> ${o.idea}</p><p><b>План:</b> ${o.plan} · <b>${o.term}</b></p><a href="${o.link}" target="_blank">Ссылка на прототип ↗</a><div class="status">${o.status==='approved'?'✓ Команда выбрана':o.status==='rejected'?'Отклонено':'Ожидает вашего решения'}</div></div>${o.status==='new'?`<div class="offer-actions"><button class="secondary approve" data-offer="${o.id}" data-status="approved">Выбрать</button><button class="secondary reject" data-offer="${o.id}" data-status="rejected">Отклонить</button></div>`:''}</article>`}).join('')}</div>`:'<p class="intro">Пока нет предложений. Они появятся здесь после откликов команд.</p>'}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').classList.remove('hidden')} function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
renderCatalog();
document.addEventListener('click',e=>{let go=e.target.closest('[data-go]');if(go){show(go.dataset.go);return}let nav=e.target.closest('.nav-item');if(nav){show(nav.dataset.view);if(nav.dataset.view==='offers')renderOffers();return}let task=e.target.closest('[data-task]');if(task)detail(task.dataset.task);let chip=e.target.closest('[data-theme]');if(chip){selectedTheme=chip.dataset.theme;$$('[data-theme]').forEach(x=>x.classList.toggle('active',x===chip));renderCatalog()}if(e.target.id==='open-offer'){let t=current;modal(`<h2>Предложить решение</h2><p>Отклик увидит только представитель бизнеса. Назначение команды происходит вручную.</p><form id="offer-form"><label>Название команды<input required name="team" placeholder="Например, Future Makers"></label><label>Идея решения<textarea required name="idea" rows="3"></textarea></label><label>Короткий план<textarea required name="plan" rows="2"></textarea></label><div class="two-col"><label>Срок<input required name="term" placeholder="4 недели"></label><label>Ссылка на прототип<input required name="link" type="url" placeholder="https://..."></label></div><button class="primary wide">Отправить отклик <span>→</span></button></form>`)}if(e.target.classList.contains('modal-close'))$('#modal').classList.add('hidden');let action=e.target.closest('[data-offer]');if(action){let o=offers.find(x=>x.id==action.dataset.offer);o.status=action.dataset.status;save();renderOffers();toast(action.dataset.status==='approved'?'Команда выбрана — ей начислены баллы за прогресс!':'Отклик отклонён')}});
$('#readiness-filter').addEventListener('change',renderCatalog);
$('#task-form').addEventListener('submit',e=>{e.preventDefault();current={title:'',theme:$('#task-theme').value,company:$('#company').value,context:$('#raw-description').value,need:$('#raw-description').value,users:'',data:'',constraints:'',result:'',success:'',contact:'',score:0};questions();show('questions')});
$('#build-card').addEventListener('click',e=>{e.preventDefault();$$('[data-field]').forEach(x=>current[x.dataset.field]=x.value);current.title=current.need.split(/[.!?]/)[0].slice(0,64)||'Новая задача';current.result='Прототип решения и рекомендации по внедрению';current.contact=current.company?`${current.company}: формат консультаций будет согласован`:'Контакт и формат консультаций будут согласованы';renderCard();show('card')});
$('#card-form').addEventListener('input',e=>{if(e.target.dataset.card){current[e.target.dataset.card]=e.target.value;current.score=calculate(current);$('#score-panel').innerHTML=`<div class="score">${current.score}<small>/100</small></div><p>${levelName(current.score)} задача</p>`;$('#score-details').innerHTML=scoreDetails(current)}});
$('#publish-task').addEventListener('click',()=>{current.score=calculate(current);current.id=Date.now();tasks.push(current);save();renderCatalog();show('catalog');toast('Задача опубликована в общем каталоге!')});
$('#modal').addEventListener('submit',e=>{if(e.target.id==='offer-form'){e.preventDefault();let d=Object.fromEntries(new FormData(e.target));offers.push({id:Date.now(),taskId:current.id,...d,status:'new'});save();$('#modal').classList.add('hidden');toast('Отклик отправлен бизнесу!')}});
