const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],W={context:10,need:10,data:20,result:15,success:15,constraints:10,users:10,contact:10};
const teams=[['CyberSaqshy','Cybersecurity, React, Python'],['Byte Busters','UX/UI, React, Node.js'],['EcoWaves','Data Science, Python'],['MedMinds','Flutter, UX Research'],['Team Alpha','Java, SQL, Product Design']].map((x,i)=>({id:i+1,name:x[0],skills:x[1]}));
function score(t){return Object.entries(W).reduce((n,[k,w])=>n+(String(t[k]||'').trim().length>8?w:0),0)}function lev(s){return s>=90?'priority':s>=70?'ready':s>=40?'working':'draft'}function lname(s){return{priority:'Приоритетная',ready:'Готовая',working:'Рабочая',draft:'Черновик'}[lev(s)]}
const base=[
['Қоймадағы тауар қалдығын автоматтандыру','Smart City','Altyn Market','Дүкенде тауар қалдығы қолмен кестеде жүргізіледі.','Тауар қалдығын бақылауды автоматтандыру.','Қойма қызметкерлері және менеджерлер','Сату кестелері және тауар тізімі','4 апта','Қалдықты бақылау прототипі','Қалдықтағы қателерді 30% азайту','Айдана, аптасына бір Zoom'],
['Пациенттерге дәрігерге жазылуды жеңілдету','HealthTech','MedCare','Клиникаға жазылу үшін көп қоңырау түседі.','Жазылу жолын түсініктірек ету.','Пациенттер мен администраторлар','Анонимді қоңырау статистикасы','4 апта, медициналық картаға қолжетімсіз','Интерактивті жазылу прототипі','',''],
['Университет асханасындағы тағам қалдығын азайту','EcoTech','Green Campus','Асхана дайын тағамды жиі есептен шығарады.','Сұранысты болжау арқылы шығынды азайту.','Асхана қызметкерлері','Күнделікті сату және мәзір деректері','6 апта','','',''],
['Студенттердің қаржылық сауатын арттыру','FinTech','Qadam Bank','Жас клиенттер қаржы құралдарын аз қолданады.','Қаржыны оқытудың қызықты форматын жасау.','17–23 жастағы студенттер','Сауалнама және брендбук','5 апта, mobile web','Кликабельді прототип','Қолданушылардың 70% терминдерді түсінеді','Мади, Telegram'],
['Қалалық мәселелерге кері байланыс сервисі','Smart City','Қалалық лаборатория','Тұрғындар мәселені әртүрлі арнамен хабарлайды.','Өтініштерді бір жерге жинау жолын табу.','Қала тұрғындары','','','','','']
].map((x,i)=>{let[t,title,company,context,need,users,data,constraints,result,success,contact]=[x[1],x[0],...x.slice(2)];let o={id:i+1,title,theme:t,company,context,need,users,data,constraints,result,success,contact,status:'published',points:0};o.score=score(o);return o});
let tasks=JSON.parse(localStorage.getItem('impact-v2-tasks')||'null')||base,proposals=JSON.parse(localStorage.getItem('impact-v2-proposals')||'null')||[[1,1,1,'Қалдық өзгерісін көрсететін қауіпсіз дашборд.','Зерттеу → деректер → MVP','14 күн'],[2,1,5,'QR және штрихкодпен тауар есебі.','UX → прототип → тест','20 күн'],[3,2,4,'Пациентке ыңғайлы жазылу сценарийі.','Интервью → UX → тест','3 апта'],[4,3,3,'Мәзірге сұранысты болжау моделі.','Талдау → дашборд → пилот','5 апта'],[5,4,2,'Геймификацияланған қаржы симуляторы.','Сценарий → UI → prototype','4 апта']].map(x=>({id:x[0],taskId:x[1],teamId:x[2],idea:x[3],plan:x[4],term:x[5],link:'https://github.com',status:'new'}));let current,questions,theme='all';const save=()=>{localStorage.setItem('impact-v2-tasks',JSON.stringify(tasks));localStorage.setItem('impact-v2-proposals',JSON.stringify(proposals))};const missing=t=>Object.keys(W).filter(k=>String(t[k]||'').trim().length<=8);const hint=t=>{let m=missing(t);return m.length?`${t.score}/100 — ${lname(t.score)}. Жоғары балл үшін: ${m.slice(0,2).join(', ')} өрісін толтырыңыз.`:'100/100 — тапсырма толық дайын.'};
function view(id){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$('#view-title').textContent={catalog:'Каталог',create:'Новая задача',questions:'AI-уточнение',card:'Карточка',detail:'Задача',offers:'Предложения'}[id]||'Платформа';window.scrollTo(0,0)}
function catalog(){let host=$('#task-grid');host.innerHTML='<p class="intro">Задачи загружаются…</p>';setTimeout(()=>{let f=$('#readiness-filter').value,a=tasks.filter(t=>(theme==='all'||t.theme===theme)&&(f==='all'||lev(t.score)===f)).sort((a,b)=>b.score-a.score);$('#task-count').textContent=`${tasks.length} задач`;host.innerHTML=a.length?a.map(t=>`<article class="task"><div class="task-meta"><span class="tag">${t.theme}</span><span class="readiness ${lev(t.score)}">${lname(t.score)}</span></div><h3>${t.title}</h3><p>${t.need}</p><div class="task-foot"><span class="score-pill"><b>${t.score}</b>/100</span><button class="view-link" data-task="${t.id}">Смотреть →</button></div></article>`).join(''):'<p class="intro">Тапсырма табылмады. Фильтрді өзгертіңіз.</p>'},150)}
function qscreen(){questions=mockAI.analyze({description:current.need,theme:current.theme}).questions;$('#questions-form').innerHTML=questions.map((q,i)=>`<div class="question"><b>${i+1}. ${q.question}</b><textarea data-field="${q.field}" placeholder="${q.placeholder}" rows="3"></textarea></div>`).join('')+`<p class="soft">Mock AI prompt: “${mockAI.prompt}”</p>`}
function details(t){return Object.entries(W).map(([k,w])=>{let ok=String(t[k]||'').trim().length>8;return`<div class="score-row"><div><span>${k}</span><b>${ok?w:0}/${w}</b></div><div class="bar"><i style="width:${ok?100:0}%"></i></div></div>`}).join('')}
function card(){current.score=score(current);$('#score-panel').innerHTML=`<div class="score">${current.score}<small>/100</small></div><p>${hint(current)}</p>`;$('#score-details').innerHTML=details(current);let f=[['title','Название задачи'],['context','Контекст'],['need','Потребность'],['users','Пользователи'],['data','Данные и материалы'],['constraints','Ограничения'],['result','Ожидаемый результат'],['success','Success criteria'],['contact','Контакт']];$('#card-form').innerHTML=f.map(x=>`<label>${x[1]}<textarea data-card="${x[0]}" rows="${x[0]==='title'?1:3}">${current[x[0]]||''}</textarea></label>`).join('')}
function showTask(id){current=tasks.find(x=>x.id==id);let t=current;$('#detail-content').innerHTML=`<div class="detail-hero"><div class="detail-top"><span class="tag">${t.theme}</span><span class="readiness ${lev(t.score)}">${lname(t.score)} · ${t.score}/100</span></div><h1>${t.title}</h1><p class="intro">${t.need}</p><p class="soft">${hint(t)}</p></div><div class="detail-content"><div>${[['Контекст',t.context],['Пайдаланушылар',t.users],['Деректер',t.data],['Күтілетін нәтиже',t.result],['Success criteria',t.success],['Шектеулер',t.constraints]].map(x=>`<div class="info-block"><h3>${x[0]}</h3><p>${x[1]||'Не указано'}</p></div>`).join('')}</div><aside class="detail-side"><h3>Есть идея решения?</h3><p>Идея, жоспар, мерзім және прототип сілтемесін жіберіңіз.</p><button class="primary" id="open-offer">Откликнуться <span>→</span></button><p><b>Контакт:</b><br>${t.contact||'Уточняется'}</p></aside></div>`;view('detail')}
function offers(){let h=$('#offers-content');h.innerHTML=proposals.length?`<div class="offer-list">${proposals.map(o=>{let t=tasks.find(x=>x.id===o.taskId),tm=teams.find(x=>x.id===o.teamId);return`<article class="offer"><div><span class="tag">${t.title}</span><h3>${tm.name}</h3><p><b>Идея:</b> ${o.idea}</p><p><b>План:</b> ${o.plan} · <b>${o.term}</b></p><a href="${o.link}" target="_blank" rel="noopener">Ссылка на прототип ↗</a><div class="status">${o.status==='approved'?'✓ Таңдалды · +25 game points':o.status==='rejected'?'Отклонено':'Ожидает вашего решения'}</div></div>${o.status==='new'?`<div class="offer-actions"><button class="secondary approve" data-offer="${o.id}" data-status="approved">Выбрать</button><button class="secondary reject" data-offer="${o.id}" data-status="rejected">Отклонить</button></div>`:''}</article>`}).join('')}</div>`:'<p class="intro">Пока нет предложений.</p>'}
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}function needAuth(){if(window.auth&&!auth.user){auth.open();return false}return true}function modal(x){$('#modal-content').innerHTML=x;$('#modal').classList.remove('hidden')}
catalog();$('#readiness-filter').onchange=catalog;document.addEventListener('click',e=>{let g=e.target.closest('[data-go]');if(g){if(g.dataset.go==='create'&&!needAuth())return;view(g.dataset.go);return}let n=e.target.closest('.nav-item');if(n){if(n.dataset.view==='create'&&!needAuth())return;view(n.dataset.view);if(n.dataset.view==='offers')offers();return}let t=e.target.closest('[data-task]');if(t)return showTask(t.dataset.task);let c=e.target.closest('[data-theme]');if(c){theme=c.dataset.theme;$$('[data-theme]').forEach(x=>x.classList.toggle('active',x===c));catalog();return}if(e.target.id==='open-offer'){if(!needAuth())return;modal(`<h2>Предложить решение</h2><form id="offer-form"><label>Команда<select name="teamId">${teams.map(x=>`<option value="${x.id}">${x.name} — ${x.skills}</option>`).join('')}</select></label><label>Идея решения<textarea required name="idea"></textarea></label><label>Короткий план<textarea required name="plan"></textarea></label><label>Срок<input required name="term" placeholder="14 күн"></label><label>Ссылка на прототип<input required name="link" type="url" placeholder="https://..."></label><button class="primary wide">Отправить отклик</button></form>`)}let a=e.target.closest('[data-offer]');if(a){let o=proposals.find(x=>x.id==a.dataset.offer);o.status=a.dataset.status;if(o.status==='approved'){let t=tasks.find(x=>x.id===o.taskId);t.status='selected';t.points=(t.points||0)+25}save();offers();toast(o.status==='approved'?'Команда таңдалды: +25 game points':'Отклик отклонён')}if(e.target.classList.contains('modal-close'))$('#modal').classList.add('hidden')});
$('#task-form').onsubmit=e=>{e.preventDefault();let raw=$('#raw-description').value.trim();if(raw.length<12)return toast('Мәселені толығырақ жазыңыз.');current={id:Date.now(),theme:$('#task-theme').value,company:$('#company').value,need:raw,title:'',context:'',users:'',data:'',constraints:'',result:'',success:'',contact:'',points:0};qscreen();view('questions')};$('#build-card').onclick=e=>{e.preventDefault();let a={};$$('[data-field]').forEach(x=>a[x.dataset.field]=x.value);current={...current,...mockAI.buildCard({description:current.need,answers:a,theme:current.theme,company:current.company})};card();view('card')};$('#card-form').oninput=e=>{if(e.target.dataset.card){current[e.target.dataset.card]=e.target.value;card()}};$('#publish-task').onclick=()=>{if(!needAuth())return;current.score=score(current);tasks.push(current);save();catalog();view('catalog');toast('Тапсырма жарияланды!')};$('#modal').addEventListener('submit',e=>{if(e.target.id==='offer-form'){e.preventDefault();let d=Object.fromEntries(new FormData(e.target));proposals.push({id:Date.now(),taskId:current.id,teamId:+d.teamId,idea:d.idea,plan:d.plan,term:d.term,link:d.link,status:'new'});save();$('#modal').classList.add('hidden');toast('Отклик жіберілді!')}});
// AI Match: transparent skill-overlap recommendation. It never selects a team automatically.
const themeSkills={HealthTech:['python','mobile','ux'],EcoTech:['python','ai/ml','data science'],FinTech:['react','web','java','sql'],EdTech:['react','web','mobile'],"Smart City":['python','cybersecurity','react','web']};
let matchProfiles=JSON.parse(localStorage.getItem('impact-match-profiles')||'{}');
function normSkills(v){return String(v||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean)}
function matchTask(task,skills){const required=task.requirements||themeSkills[task.theme]||['web'];const matched=required.filter(x=>skills.includes(x));const pct=Math.round((matched.length/required.length)*80+(task.score/100)*20);return{required,matched,pct}}
function renderMatch(){const select=$('#match-team');select.innerHTML=teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');const first=teams[0];select.value=matchProfiles.selected||first.id;const sync=()=>{let team=teams.find(x=>x.id==select.value)||first;$('#match-skills').value=matchProfiles[team.id]||team.skills;drawMatch(team)};select.onchange=sync;sync()}
function drawMatch(team){const skills=normSkills($('#match-skills').value);const rows=tasks.map(t=>({task:t,...matchTask(t,skills)})).sort((a,b)=>b.pct-a.pct);$('#match-results').innerHTML=rows.length?rows.map(x=>`<article class="offer"><div><span class="tag">AI Match · ${x.pct}%</span><h3>${x.task.title}</h3><p><b>Сізде:</b> ${x.matched.length?x.matched.join(', '):'тікелей skill сәйкестігі жоқ'}</p><p><b>Тапсырма талаптары:</b> ${x.required.join(', ')}</p><p class="soft">Recommendation only — команда автоматты таңдалмайды.</p></div><div class="offer-actions"><button class="secondary" data-task="${x.task.id}">Смотреть</button></div></article>`).join(''):'<p class="intro">Тапсырмалар әлі жоқ.</p>'}
$('#save-match-profile').onclick=()=>{const id=$('#match-team').value;matchProfiles[id]=$('#match-skills').value;matchProfiles.selected=id;localStorage.setItem('impact-match-profiles',JSON.stringify(matchProfiles));drawMatch(teams.find(t=>t.id==id));toast('AI Match recommendations жаңартылды')};
document.addEventListener('click',e=>{if(e.target.closest('.nav-item[data-view="match"]')){if(!needAuth())return;setTimeout(renderMatch,0)}});
